LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_TAGS := optional

include $(BUILD_SYSTEM)/base_rules.mk

$(LOCAL_BUILT_MODULE): MY_CRITERION_TYPES_FILE := $(CRITERION_TYPES_FILE)
$(LOCAL_BUILT_MODULE): MY_ANDROID_AUDIO_BASE_HEADER_FILE := $(ANDROID_AUDIO_BASE_HEADER_FILE)
$(LOCAL_BUILT_MODULE): MY_AUDIO_POLICY_CONFIGURATION_FILE := $(AUDIO_POLICY_CONFIGURATION_FILE)
$(LOCAL_BUILT_MODULE): MY_CRITERION_TOOL := $(HOST_OUT)/bin/buildPolicyCriterionTypes.py
$(LOCAL_BUILT_MODULE): $(LOCAL_REQUIRED_MODULES) $(LOCAL_ADDITIONAL_DEPENDENCIES) \
    buildPolicyCriterionTypes.py \
    $(CRITERION_TYPES_FILE) \
    $(ANDROID_AUDIO_BASE_HEADER_FILE)

	"$(MY_CRITERION_TOOL)" \
		--androidaudiobaseheader "$(MY_ANDROID_AUDIO_BASE_HEADER_FILE)" \
		--audiopolicyconfigurationfile "$(MY_AUDIO_POLICY_CONFIGURATION_FILE)" \
		--criteriontypes "$(MY_CRITERION_TYPES_FILE)" \
		--outputfile "$(@)"

# Clear variables for further use
CRITERION_TYPES_FILE :=
ANDROID_AUDIO_BASE_HEADER_FILE :=
AUDIO_POLICY_CONFIGURATION_FILE :=
