#!/bin/bash

# Runs OboeTester with different buffer sizes.
# Uses cable_breaker to allow device to enter
# suspend when display is off.
#
# Works on Pixel devices with eng/userdebug(root) builds

##############
# Test Configuration

# Array of buffer size in milliseconds for testing
# negative values use deep buffer
time_array=(20000 10000 5000 2000 -500 -1000)
# time_array=(20000)

# Duration of each test in seconds
# Override with -d [SECONDS]
duration=600

# Whether perfetto is used
# Override with -p
use_perfetto=""

# Configuration to use for oboetester
configuration="--ei sample_rate 48000 --es out_channel_mask stereo --es out_format pcm_16_bit"

# EXAMPLES:
#
# Use perfetto with a duration of 120 seconds
#
# $ . oboe_powertest_script -p -d 120

##############
# Loop through all the command-line arguments until none are left.
while (( "$#" )); do
  case "$1" in
    # If the argument is -p, print "hello".
    -p)
      use_perfetto="true"
      # Consume the -p flag by shifting the arguments.
      shift
      ;;
    # If the argument is -d, handle setting the duration.
    -d)
      # Check if there is a next argument and it's not another flag.
      if [ -n "$2" ] && ! [[ "$2" =~ ^- ]]; then
        # Check if the provided value is an integer.
        if [[ "$2" =~ ^[0-9]+$ ]]; then
          # Assign the next argument to the duration variable.
          duration="$2"
          # Consume both the -d flag and its value by shifting twice.
          shift 2
        else
          # If the value is not an integer, print an error and exit.
          echo "Error: -d option requires an integer value." >&2
          exit 1
        fi
      else
        # If no value is provided for -d, print an error to standard error and exit.
        echo "Error: -d option requires a value." >&2
        exit 1
      fi
      ;;
    # Handle any other unsupported arguments.
    *)
      echo "Error: Unsupported argument $1" >&2
      exit 1
      ;;
  esac
done

# After parsing all arguments, check if the duration variable was set
# and print its value for confirmation.
if [ -n "$duration" ]; then
  echo "Duration was set to: $duration"
fi
if [ -n "$use_perfetto" ]; then
  echo "Tracing with perfetto"
fi
if [ -n "$configuration" ]; then
  echo "Configuration: $configuration"
fi

##############
# System Configuration
# Configure 5 second screen timeout
adb shell settings put system doff_screen_timeout_ms 5000
adb shell settings put system screen_off_timeout 5000

# Set media volume to 1
adb shell cmd media_session volume --set 1

# Enable AudioFlinger power stats
adb shell setenforce 0
adb shell setprop persist.audio.power_stats.enabled true

# Test loop:  iterate through each buffer size in time
for time in "${time_array[@]}"; do
  # ensure oboetester foreground service set properly
  echo "restarting oboetester"
  adb shell pkill oboetester

  # ensure similar stats collection state
  echo "restarting audioserver and waiting 5 seconds"
  adb shell pkill audio
  sleep 5

  # echo "$OUT"
  echo "----------------------------------------------------------------"

  if [ -n "$use_perfetto" ]; then
    # we can't use background with suspend
    # adb shell perfetto audio sched freq hal --background --time "${duration}s" --out "/data/misc/perfetto-traces/trace_${time}.pf"
    adb shell "echo ' \
write_into_file: true \
file_write_period_ms: 1000000000 \
buffers { \
  size_kb: 32768 \
} \
buffers: { \
    size_kb: 2048 \
} \
buffers: { \
    size_kb: 1024 \
} \
data_sources { \
  config { \
    name: \"linux.ftrace\" \
    target_buffer: 0 \
    ftrace_config { \
      atrace_categories: \"audio\" \
      atrace_categories: \"sched\" \
      atrace_categories: \"freq\" \
      atrace_categories: \"hal\" \
      symbolize_ksyms: true \
    } \
  } \
} \
data_sources { \
  config { \
    name: \"linux.process_stats\" \
    target_buffer: 1 \
  } \
} \
data_sources { \
  config { \
    name: \"linux.system_info\" \
    target_buffer: 2 \
  } \
} \
data_sources: { \
    config { \
        name: \"android.packages_list\" \
        target_buffer: 2 \
    } \
} \
' | perfetto -c - --txt --detach=oboeperf1 -o \"/data/misc/perfetto-traces/trace_${time}.pf\""

  fi # use_perfetto

  if [[ $time -lt 0 ]]; then

    frames=$((time * -48))
    abstime=$((time * -1))
    echo "launching oboetester (deep buffer): testing $duration seconds  buffer: $frames frames $abstime ms"

    # the following prints out the intent
    adb shell am start -n com.mobileer.oboetester/.MainActivity --es test output $configuration -es out_perf powersave --ez background true --ei duration 1000000 --ez foreground_service 1 --ei buffer_capacity $frames

    # classic pcm offload
    # adb shell am start -n com.mobileer.oboetester/.MainActivity --es test output $configuration --es out_perf powersave_offload --ez out_use_mmap false --ez background true --ei duration 1000000 --ez foreground_service 1 --ei buffer_frames 48000

  else

    frames=$((time * 48))
    echo "launching oboetester (mmap offload): testing $duration seconds  buffer: $frames frames $time ms"
    adb shell am start -n com.mobileer.oboetester/.MainActivity --es test output $configuration --es out_perf powersave_offload --ez out_use_mmap true --es out_sharing exclusive --ez background true --ei duration 1000000 --ez foreground_service 1 --ei buffer_frames $frames
  fi

  # adb shell input keyevent KEYCODE_SLEEP

  echo "suspending now by cable_breaker"
  adb shell cable_breaker -a break:$duration

  # add 5 seconds for the track to complete and shut down
  sleep 5
  sleep $duration

  # we should be reconnected now.

  if [ -n "$use_perfetto" ]; then
    adb shell perfetto --attach=oboeperf1 --stop
    adb pull "/data/misc/perfetto-traces/trace_${time}.pf"
  fi

  # stop oboetester
  adb shell am force-stop com.mobileer.oboetester

  # get stats from AudioFlinger
  sleep 3
  adb shell dumpsys media.audio_flinger | grep -A 28  "uid.*com.mobileer.oboetester"

done
